name: continuous-integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: "npm"
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm run lint:eslint
      - run: npm run build
