permissions:
    contents: write

name: Release Obsidian plugin

on:
    push:
        tags:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5

            - name: Use Node.js
              uses: actions/setup-node@v5
              with:
                  node-version: "22.14.0"

            - name: Build plugin
              run: |
                  npm install
                  npm run build

            - name: Create release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  gh release create "${{ github.ref_name }}" \
                    --title "${{ github.ref_name }}" \
                    --generate-notes \
                    --latest \
                    main.js manifest.json styles.css
