name: Release Obsidian plugin

on:
    push:
        tags:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

			- name: Set release version
				id: vars
				run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"

            - name: Build plugin
              run: |
                  npm install
                  npm run build

            - name: Create release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
				  gh release create "${{ steps.vars.outputs.tag }}" \
				  	--title="${{ steps.vars.outputs.tag }}" \
					--notes-from-tag \
					--latest \
					main.js manifest.json styles.css
